version: '3'
services:
  backend:
    image: amazoncorretto:latest
    volumes:
      - ./backend:/app/backend
    command: sh -c "apt-get update && apt-get install -y openjdk-17-jdk && chmod -R 771 /app/backend && chown -R user:user /app/backend"

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=sevedemo
      - MYSQL_USER=pigiatasti
      - MYSQL_PASSWORD=odiojava
    command: sh -c "mysql -u root -p 3306 -D sevedemo < dbdupm.sql"

  frontend:
    image: httpd:2.4
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 80:80
