version: '3.8'
services:
  spring:
    image: debian:latest
    volumes:
      - ../backend:/app/backend
      - ../frontend:/var/www/html
      - ../db/dump.sql:/app/db/dump.sql
    command: sh -c "
          apt-get update -y
          && apt-get install -y mariadb-client mariadb-server openjdk-17-jdk nginx
          && chmod -R 771 /app/*
          && mysql -u root -p sevedemo < /app/db/dump.sql
          && chown -R $(whoami):$(whoami) /app/*
          && cd /app/backend
          && ./mvnw clean install
          && ./mvnw spring-boot:run"
          "
