version: '3'

services:
  db:
    image: mysql:8.0.33-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql
    ports:
      - '3306:3306'
  app:
    image: openjdk:17-jdk-alpine3.14
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./app.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
  apache:
    image: httpd:2.4.57-bookworm
    ports:
      - '80:80'
    depends_on:
      - app
      - worker
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - html:/usr/local/apache2/htdocs/
  worker:
    image: alpine:3.18.2
    volumes:
      - ../frontend:/html
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]

volumes:
  html:
